#!/bin/bash
set -e

../verify-docker-versions

export INTEGRATION_VERSION=$(git describe --tags --abbrev=0)
export MENDER_ARTIFACT_VERSION=$(../extra/release_tool.py -g mender-artifact)
export MENDER_VERSION=$(../extra/release_tool.py -g mender)
export MENDER_DEB_PACKAGE_VERSION=$MENDER_VERSION
export GATEWAY_IP=$(ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p')

exec docker-compose \
     -p menderproduction \
     -f ../docker-compose.yml \
     -f ../docker-compose.storage.minio.yml \
     -f ./prod.yml \
     "$@"
